apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: ">=6.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    service:
      type: ClusterIP
    grafana:
      grafana.ini:
        server:
          root_url: http://localhost:3000
        auth.generic_oauth:
          enabled: true
          name: Keycloak
          allow_sign_up: true
          scopes: openid email profile
          auth_url: http://keycloak.keycloak.svc.cluster.local:8080/realms/demo/protocol/openid-connect/auth
          token_url: http://keycloak.keycloak.svc.cluster.local:8080/realms/demo/protocol/openid-connect/token
          api_url: http://keycloak.keycloak.svc.cluster.local:8080/realms/demo/protocol/openid-connect/userinfo
    # Env mapping: liest secret grafana-oauth und setzt GF_AUTH_GENERIC_OAUTH_*
    env:
      - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: grafana-oauth
            key: client-id
      - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: grafana-oauth
            key: client-secret
