apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: 9.4.x
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - grafana.local
      tls: [] # lokal HTTP
    envFromSecret: external-secrets/grafana-oidc
    grafana.ini:
      server:
        root_url: "http://grafana.local"
      security:
        disable_initial_admin_creation: true # keine lokale admin:admin Erstellung
      auth:
        disable_login_form: true # nur OIDC
        oauth_auto_login: true
      auth.generic_oauth:
        enabled: true
        name: Keycloak
        scopes: "openid profile email"
        # client_id/secret kommen aus ENV (GF_AUTH_GENERIC_OAUTH_CLIENT_ID/_SECRET)
        auth_url: "http://keycloak.local/realms/dev/protocol/openid-connect/auth"
        token_url: "http://keycloak.local/realms/dev/protocol/openid-connect/token"
        api_url: "http://keycloak.local/realms/dev/protocol/openid-connect/userinfo"
        allow_sign_up: true
        # Beispiel: Gruppen -> Rollen-Mapping
        role_attribute_path: >-
          contains(groups[*], 'grafana-admin') && 'Admin' ||
          contains(groups[*], 'grafana-editor') && 'Editor' || 'Viewer'
