apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-kv
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso"
