apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: secrets/keycloak
        property: admin-password
