apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: keycloak # Vault-Pfad: secret/keycloak
        property: admin-password
