apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets-repo
        namespace: flux-system
      # if you don't have HelmRepository named external-secrets-repo, add it pointing to https://charts.external-secrets.io
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true
