apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: ">=0.30.1 <0.31.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  values:
    ui:
      enabled: true
      service:
        type: ClusterIP
    server:
      dev:
        enabled: true
        devRootToken: "root" # lokal PoC; merk dir den token, aber NICHT ins Git committen
